### ISSUE TITLE
Handle invalid string when calling `frame variable`

### ISSUE THREAD

**Issue by csk-ableton** [christopher-strack/sublime-lldb#45]
JSON error when calling `frame variable`.

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Users/csk/Library/Application Support/Sublime Text 3/Packages/sublime-lldb/lldbclient/client.py", line 51, in _process_event_queue
    self.send_json(event)
  File "/Users/csk/Library/Application Support/Sublime Text 3/Packages/sublime-lldb/ipc/client.py", line 25, in send_json
    write_json(self.socket, data)
  File "/Users/csk/Library/Application Support/Sublime Text 3/Packages/sublime-lldb/ipc/message.py", line 30, in write_json
    data = json.dumps(data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 243, in dumps
    return _default_encoder.encode(obj)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xff in position 1452: invalid start byte
```

**Comment by christopher-strack** [comment]
Try `ensure_ascii=False` when calling `dumps` and `loads`
